name = "cron"
version = "0.1.0"

description = "cron expression lib for gleam"
licences = ["MIT"]
repository = { type = "github", user = "lost22git", repo = "cron" }
links = [{ title = "Website", href = "https://github.com/lost22git/cron" }]

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
